//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;

namespace JIRAPortalCliente
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.soap.servicos")]
    public partial class ServicoPortalClienteException
    {
        
        private Exception servicoPortalClienteException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServicoPortalClienteException", IsNullable=true, Order=0)]
        public Exception ServicoPortalClienteException1
        {
            get
            {
                return this.servicoPortalClienteException1Field;
            }
            set
            {
                this.servicoPortalClienteException1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sac.soap.servicos")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jira.model/xsd")]
    public partial class CondutorAX
    {
        
        private string celularField;
        
        private string cnhField;
        
        private string criacaoField;
        
        private string emailField;
        
        private string gestorFrotaIdField;
        
        private string gestorFrotaMasterIdField;
        
        private string idField;
        
        private string identificacaoField;
        
        private string nomeField;
        
        private string profissaoField;
        
        private string rgField;
        
        private string telefoneField;
        
        private string telefone1Field;
        
        private string vencimentoCnhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string celular
        {
            get
            {
                return this.celularField;
            }
            set
            {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cnh
        {
            get
            {
                return this.cnhField;
            }
            set
            {
                this.cnhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string criacao
        {
            get
            {
                return this.criacaoField;
            }
            set
            {
                this.criacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string gestorFrotaId
        {
            get
            {
                return this.gestorFrotaIdField;
            }
            set
            {
                this.gestorFrotaIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string gestorFrotaMasterId
        {
            get
            {
                return this.gestorFrotaMasterIdField;
            }
            set
            {
                this.gestorFrotaMasterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string identificacao
        {
            get
            {
                return this.identificacaoField;
            }
            set
            {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string profissao
        {
            get
            {
                return this.profissaoField;
            }
            set
            {
                this.profissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string rg
        {
            get
            {
                return this.rgField;
            }
            set
            {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string telefone
        {
            get
            {
                return this.telefoneField;
            }
            set
            {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string telefone1
        {
            get
            {
                return this.telefone1Field;
            }
            set
            {
                this.telefone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string vencimentoCnh
        {
            get
            {
                return this.vencimentoCnhField;
            }
            set
            {
                this.vencimentoCnhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.soap.servicos")]
    public partial class ServicoPortalClienteRemoteException
    {
        
        private RemoteException remoteExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public RemoteException RemoteException
        {
            get
            {
                return this.remoteExceptionField;
            }
            set
            {
                this.remoteExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rmi.java/xsd")]
    public partial class RemoteException : IOException
    {
        
        private object causeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoteException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://io.java/xsd")]
    public partial class IOException
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sac.soap.servicos", ConfigurationName="JIRAPortalCliente.ServicoPortalClientePortType")]
    public interface ServicoPortalClientePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:consultacondutorAX", ReplyAction="urn:consultacondutorAXResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.consultacondutorAXResponse> consultacondutorAXAsync(JIRAPortalCliente.consultacondutorAXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getByteAttachmentsIssue", ReplyAction="urn:getByteAttachmentsIssueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JIRAPortalCliente.ServicoPortalClienteException), Action="urn:getByteAttachmentsIssueServicoPortalClienteException", Name="ServicoPortalClienteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getByteAttachmentsIssueResponse> getByteAttachmentsIssueAsync(JIRAPortalCliente.getByteAttachmentsIssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CriaDadosAtendimento", ReplyAction="urn:CriaDadosAtendimentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JIRAPortalCliente.ServicoPortalClienteRemoteException), Action="urn:CriaDadosAtendimentoServicoPortalClienteRemoteException", Name="ServicoPortalClienteRemoteException")]
        [System.ServiceModel.FaultContractAttribute(typeof(JIRAPortalCliente.ServicoPortalClienteException), Action="urn:CriaDadosAtendimentoServicoPortalClienteException", Name="ServicoPortalClienteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.CriaDadosAtendimentoResponse> CriaDadosAtendimentoAsync(JIRAPortalCliente.CriaDadosAtendimentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:inputAttachamentInIssue", ReplyAction="urn:inputAttachamentInIssueResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.inputAttachamentInIssueResponse> inputAttachamentInIssueAsync(JIRAPortalCliente.inputAttachamentInIssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:quickSearch", ReplyAction="urn:quickSearchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.quickSearchResponse> quickSearchAsync(JIRAPortalCliente.quickSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getIssueObjectByIssueKey", ReplyAction="urn:getIssueObjectByIssueKeyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getIssueObjectByIssueKeyResponse> getIssueObjectByIssueKeyAsync(JIRAPortalCliente.getIssueObjectByIssueKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCustomFieldsByIssueType", ReplyAction="urn:getCustomFieldsByIssueTypeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getCustomFieldsByIssueTypeResponse> getCustomFieldsByIssueTypeAsync(JIRAPortalCliente.getCustomFieldsByIssueTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CreateCommentInIssue", ReplyAction="urn:CreateCommentInIssueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JIRAPortalCliente.ServicoPortalClienteException), Action="urn:CreateCommentInIssueServicoPortalClienteException", Name="ServicoPortalClienteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.CreateCommentInIssueResponse> CreateCommentInIssueAsync(JIRAPortalCliente.CreateCommentInIssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:progressWorkflowApp", ReplyAction="urn:progressWorkflowAppResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.progressWorkflowAppResponse> progressWorkflowAppAsync(JIRAPortalCliente.progressWorkflowAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CriaDadosAtendimentoAPP", ReplyAction="urn:CriaDadosAtendimentoAPPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JIRAPortalCliente.ServicoPortalClienteRemoteException), Action="urn:CriaDadosAtendimentoAPPServicoPortalClienteRemoteException", Name="ServicoPortalClienteRemoteException")]
        [System.ServiceModel.FaultContractAttribute(typeof(JIRAPortalCliente.ServicoPortalClienteException), Action="urn:CriaDadosAtendimentoAPPServicoPortalClienteException", Name="ServicoPortalClienteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.CriaDadosAtendimentoAPPResponse> CriaDadosAtendimentoAPPAsync(JIRAPortalCliente.CriaDadosAtendimentoAPPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:condutorAxInsertOrUpdade")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task condutorAxInsertOrUpdadeAsync(JIRAPortalCliente.condutorAxInsertOrUpdade request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAttachmentsIssue", ReplyAction="urn:getAttachmentsIssueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JIRAPortalCliente.ServicoPortalClienteException), Action="urn:getAttachmentsIssueServicoPortalClienteException", Name="ServicoPortalClienteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getAttachmentsIssueResponse> getAttachmentsIssueAsync(JIRAPortalCliente.getAttachmentsIssueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultacondutorAX", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class consultacondutorAXRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public JIRAPortalCliente.CondutorAX condutor;
        
        public consultacondutorAXRequest()
        {
        }
        
        public consultacondutorAXRequest(JIRAPortalCliente.CondutorAX condutor)
        {
            this.condutor = condutor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultacondutorAXResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class consultacondutorAXResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public JIRAPortalCliente.CondutorAX[] @return;
        
        public consultacondutorAXResponse()
        {
        }
        
        public consultacondutorAXResponse(JIRAPortalCliente.CondutorAX[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByteAttachmentsIssue", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getByteAttachmentsIssueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string issueKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sattachmentId;
        
        public getByteAttachmentsIssueRequest()
        {
        }
        
        public getByteAttachmentsIssueRequest(string issueKey, string sattachmentId)
        {
            this.issueKey = issueKey;
            this.sattachmentId = sattachmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByteAttachmentsIssueResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getByteAttachmentsIssueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getByteAttachmentsIssueResponse()
        {
        }
        
        public getByteAttachmentsIssueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CriaDadosAtendimento", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class CriaDadosAtendimentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml;
        
        public CriaDadosAtendimentoRequest()
        {
        }
        
        public CriaDadosAtendimentoRequest(string xml)
        {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CriaDadosAtendimentoResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class CriaDadosAtendimentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public CriaDadosAtendimentoResponse()
        {
        }
        
        public CriaDadosAtendimentoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inputAttachamentInIssue", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class inputAttachamentInIssueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string anexoXML;
        
        public inputAttachamentInIssueRequest()
        {
        }
        
        public inputAttachamentInIssueRequest(string anexoXML)
        {
            this.anexoXML = anexoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inputAttachamentInIssueResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class inputAttachamentInIssueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public inputAttachamentInIssueResponse()
        {
        }
        
        public inputAttachamentInIssueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="quickSearch", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class quickSearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string placa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cpf;
        
        public quickSearchRequest()
        {
        }
        
        public quickSearchRequest(string placa, string cpf)
        {
            this.placa = placa;
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="quickSearchResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class quickSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public quickSearchResponse()
        {
        }
        
        public quickSearchResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getIssueObjectByIssueKey", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getIssueObjectByIssueKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pkey;
        
        public getIssueObjectByIssueKeyRequest()
        {
        }
        
        public getIssueObjectByIssueKeyRequest(string pkey)
        {
            this.pkey = pkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getIssueObjectByIssueKeyResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getIssueObjectByIssueKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getIssueObjectByIssueKeyResponse()
        {
        }
        
        public getIssueObjectByIssueKeyResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomFieldsByIssueType", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getCustomFieldsByIssueTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string issueType;
        
        public getCustomFieldsByIssueTypeRequest()
        {
        }
        
        public getCustomFieldsByIssueTypeRequest(string issueType)
        {
            this.issueType = issueType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomFieldsByIssueTypeResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getCustomFieldsByIssueTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getCustomFieldsByIssueTypeResponse()
        {
        }
        
        public getCustomFieldsByIssueTypeResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCommentInIssue", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class CreateCommentInIssueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml;
        
        public CreateCommentInIssueRequest()
        {
        }
        
        public CreateCommentInIssueRequest(string xml)
        {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCommentInIssueResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class CreateCommentInIssueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public CreateCommentInIssueResponse()
        {
        }
        
        public CreateCommentInIssueResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="progressWorkflowApp", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class progressWorkflowAppRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pkey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transitionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string comment;
        
        public progressWorkflowAppRequest()
        {
        }
        
        public progressWorkflowAppRequest(string pkey, string transitionId, string comment)
        {
            this.pkey = pkey;
            this.transitionId = transitionId;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="progressWorkflowAppResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class progressWorkflowAppResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        public bool @return;
        
        public progressWorkflowAppResponse()
        {
        }
        
        public progressWorkflowAppResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CriaDadosAtendimentoAPP", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class CriaDadosAtendimentoAPPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string placa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cpf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string km;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string endereco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string detalhamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataAgendamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cnpjFornecedor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoManutencao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string preAgendamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoAssistencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cidade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string terceiros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subcategoria;
        
        public CriaDadosAtendimentoAPPRequest()
        {
        }
        
        public CriaDadosAtendimentoAPPRequest(string placa, string cpf, string km, string endereco, string detalhamento, string dataAgendamento, string cnpjFornecedor, string tipoManutencao, string preAgendamento, string tipoAssistencia, string estado, string cidade, string terceiros, string subcategoria)
        {
            this.placa = placa;
            this.cpf = cpf;
            this.km = km;
            this.endereco = endereco;
            this.detalhamento = detalhamento;
            this.dataAgendamento = dataAgendamento;
            this.cnpjFornecedor = cnpjFornecedor;
            this.tipoManutencao = tipoManutencao;
            this.preAgendamento = preAgendamento;
            this.tipoAssistencia = tipoAssistencia;
            this.estado = estado;
            this.cidade = cidade;
            this.terceiros = terceiros;
            this.subcategoria = subcategoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CriaDadosAtendimentoAPPResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class CriaDadosAtendimentoAPPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public CriaDadosAtendimentoAPPResponse()
        {
        }
        
        public CriaDadosAtendimentoAPPResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="condutorAxInsertOrUpdade", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class condutorAxInsertOrUpdade
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public JIRAPortalCliente.CondutorAX condutor;
        
        public condutorAxInsertOrUpdade()
        {
        }
        
        public condutorAxInsertOrUpdade(JIRAPortalCliente.CondutorAX condutor)
        {
            this.condutor = condutor;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jira.model/xsd")]
    public partial class Anexo
    {
        
        private string authorField;
        
        private byte[] buffField;
        
        private string datetimeField;
        
        private string filenameField;
        
        private System.Nullable<long> filesizeField;
        
        private bool filesizeFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int issueidField;
        
        private bool issueidFieldSpecified;
        
        private string mimetypeField;
        
        private string pathField;
        
        private string pkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=1)]
        public byte[] buff
        {
            get
            {
                return this.buffField;
            }
            set
            {
                this.buffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string datetime
        {
            get
            {
                return this.datetimeField;
            }
            set
            {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> filesize
        {
            get
            {
                return this.filesizeField;
            }
            set
            {
                this.filesizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filesizeSpecified
        {
            get
            {
                return this.filesizeFieldSpecified;
            }
            set
            {
                this.filesizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int issueid
        {
            get
            {
                return this.issueidField;
            }
            set
            {
                this.issueidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool issueidSpecified
        {
            get
            {
                return this.issueidFieldSpecified;
            }
            set
            {
                this.issueidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string mimetype
        {
            get
            {
                return this.mimetypeField;
            }
            set
            {
                this.mimetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string pkey
        {
            get
            {
                return this.pkeyField;
            }
            set
            {
                this.pkeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentsIssue", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getAttachmentsIssueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string issueKey;
        
        public getAttachmentsIssueRequest()
        {
        }
        
        public getAttachmentsIssueRequest(string issueKey)
        {
            this.issueKey = issueKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttachmentsIssueResponse", WrapperNamespace="http://sac.soap.servicos", IsWrapped=true)]
    public partial class getAttachmentsIssueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sac.soap.servicos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public JIRAPortalCliente.Anexo[] @return;
        
        public getAttachmentsIssueResponse()
        {
        }
        
        public getAttachmentsIssueResponse(JIRAPortalCliente.Anexo[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ServicoPortalClientePortTypeChannel : JIRAPortalCliente.ServicoPortalClientePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ServicoPortalClientePortTypeClient : System.ServiceModel.ClientBase<JIRAPortalCliente.ServicoPortalClientePortType>, JIRAPortalCliente.ServicoPortalClientePortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicoPortalClientePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicoPortalClientePortTypeClient.GetBindingForEndpoint(endpointConfiguration), ServicoPortalClientePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoPortalClientePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicoPortalClientePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoPortalClientePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicoPortalClientePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoPortalClientePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.consultacondutorAXResponse> JIRAPortalCliente.ServicoPortalClientePortType.consultacondutorAXAsync(JIRAPortalCliente.consultacondutorAXRequest request)
        {
            return base.Channel.consultacondutorAXAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.consultacondutorAXResponse> consultacondutorAXAsync(JIRAPortalCliente.CondutorAX condutor)
        {
            JIRAPortalCliente.consultacondutorAXRequest inValue = new JIRAPortalCliente.consultacondutorAXRequest();
            inValue.condutor = condutor;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).consultacondutorAXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getByteAttachmentsIssueResponse> JIRAPortalCliente.ServicoPortalClientePortType.getByteAttachmentsIssueAsync(JIRAPortalCliente.getByteAttachmentsIssueRequest request)
        {
            return base.Channel.getByteAttachmentsIssueAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.getByteAttachmentsIssueResponse> getByteAttachmentsIssueAsync(string issueKey, string sattachmentId)
        {
            JIRAPortalCliente.getByteAttachmentsIssueRequest inValue = new JIRAPortalCliente.getByteAttachmentsIssueRequest();
            inValue.issueKey = issueKey;
            inValue.sattachmentId = sattachmentId;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).getByteAttachmentsIssueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.CriaDadosAtendimentoResponse> JIRAPortalCliente.ServicoPortalClientePortType.CriaDadosAtendimentoAsync(JIRAPortalCliente.CriaDadosAtendimentoRequest request)
        {
            return base.Channel.CriaDadosAtendimentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.CriaDadosAtendimentoResponse> CriaDadosAtendimentoAsync(string xml)
        {
            JIRAPortalCliente.CriaDadosAtendimentoRequest inValue = new JIRAPortalCliente.CriaDadosAtendimentoRequest();
            inValue.xml = xml;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).CriaDadosAtendimentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.inputAttachamentInIssueResponse> JIRAPortalCliente.ServicoPortalClientePortType.inputAttachamentInIssueAsync(JIRAPortalCliente.inputAttachamentInIssueRequest request)
        {
            return base.Channel.inputAttachamentInIssueAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.inputAttachamentInIssueResponse> inputAttachamentInIssueAsync(string anexoXML)
        {
            JIRAPortalCliente.inputAttachamentInIssueRequest inValue = new JIRAPortalCliente.inputAttachamentInIssueRequest();
            inValue.anexoXML = anexoXML;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).inputAttachamentInIssueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.quickSearchResponse> JIRAPortalCliente.ServicoPortalClientePortType.quickSearchAsync(JIRAPortalCliente.quickSearchRequest request)
        {
            return base.Channel.quickSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.quickSearchResponse> quickSearchAsync(string placa, string cpf)
        {
            JIRAPortalCliente.quickSearchRequest inValue = new JIRAPortalCliente.quickSearchRequest();
            inValue.placa = placa;
            inValue.cpf = cpf;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).quickSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getIssueObjectByIssueKeyResponse> JIRAPortalCliente.ServicoPortalClientePortType.getIssueObjectByIssueKeyAsync(JIRAPortalCliente.getIssueObjectByIssueKeyRequest request)
        {
            return base.Channel.getIssueObjectByIssueKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.getIssueObjectByIssueKeyResponse> getIssueObjectByIssueKeyAsync(string pkey)
        {
            JIRAPortalCliente.getIssueObjectByIssueKeyRequest inValue = new JIRAPortalCliente.getIssueObjectByIssueKeyRequest();
            inValue.pkey = pkey;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).getIssueObjectByIssueKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getCustomFieldsByIssueTypeResponse> JIRAPortalCliente.ServicoPortalClientePortType.getCustomFieldsByIssueTypeAsync(JIRAPortalCliente.getCustomFieldsByIssueTypeRequest request)
        {
            return base.Channel.getCustomFieldsByIssueTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.getCustomFieldsByIssueTypeResponse> getCustomFieldsByIssueTypeAsync(string issueType)
        {
            JIRAPortalCliente.getCustomFieldsByIssueTypeRequest inValue = new JIRAPortalCliente.getCustomFieldsByIssueTypeRequest();
            inValue.issueType = issueType;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).getCustomFieldsByIssueTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.CreateCommentInIssueResponse> JIRAPortalCliente.ServicoPortalClientePortType.CreateCommentInIssueAsync(JIRAPortalCliente.CreateCommentInIssueRequest request)
        {
            return base.Channel.CreateCommentInIssueAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.CreateCommentInIssueResponse> CreateCommentInIssueAsync(string xml)
        {
            JIRAPortalCliente.CreateCommentInIssueRequest inValue = new JIRAPortalCliente.CreateCommentInIssueRequest();
            inValue.xml = xml;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).CreateCommentInIssueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.progressWorkflowAppResponse> JIRAPortalCliente.ServicoPortalClientePortType.progressWorkflowAppAsync(JIRAPortalCliente.progressWorkflowAppRequest request)
        {
            return base.Channel.progressWorkflowAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.progressWorkflowAppResponse> progressWorkflowAppAsync(string pkey, string transitionId, string comment)
        {
            JIRAPortalCliente.progressWorkflowAppRequest inValue = new JIRAPortalCliente.progressWorkflowAppRequest();
            inValue.pkey = pkey;
            inValue.transitionId = transitionId;
            inValue.comment = comment;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).progressWorkflowAppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.CriaDadosAtendimentoAPPResponse> JIRAPortalCliente.ServicoPortalClientePortType.CriaDadosAtendimentoAPPAsync(JIRAPortalCliente.CriaDadosAtendimentoAPPRequest request)
        {
            return base.Channel.CriaDadosAtendimentoAPPAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.CriaDadosAtendimentoAPPResponse> CriaDadosAtendimentoAPPAsync(string placa, string cpf, string km, string endereco, string detalhamento, string dataAgendamento, string cnpjFornecedor, string tipoManutencao, string preAgendamento, string tipoAssistencia, string estado, string cidade, string terceiros, string subcategoria)
        {
            JIRAPortalCliente.CriaDadosAtendimentoAPPRequest inValue = new JIRAPortalCliente.CriaDadosAtendimentoAPPRequest();
            inValue.placa = placa;
            inValue.cpf = cpf;
            inValue.km = km;
            inValue.endereco = endereco;
            inValue.detalhamento = detalhamento;
            inValue.dataAgendamento = dataAgendamento;
            inValue.cnpjFornecedor = cnpjFornecedor;
            inValue.tipoManutencao = tipoManutencao;
            inValue.preAgendamento = preAgendamento;
            inValue.tipoAssistencia = tipoAssistencia;
            inValue.estado = estado;
            inValue.cidade = cidade;
            inValue.terceiros = terceiros;
            inValue.subcategoria = subcategoria;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).CriaDadosAtendimentoAPPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task JIRAPortalCliente.ServicoPortalClientePortType.condutorAxInsertOrUpdadeAsync(JIRAPortalCliente.condutorAxInsertOrUpdade request)
        {
            return base.Channel.condutorAxInsertOrUpdadeAsync(request);
        }
        
        public System.Threading.Tasks.Task condutorAxInsertOrUpdadeAsync(JIRAPortalCliente.CondutorAX condutor)
        {
            JIRAPortalCliente.condutorAxInsertOrUpdade inValue = new JIRAPortalCliente.condutorAxInsertOrUpdade();
            inValue.condutor = condutor;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).condutorAxInsertOrUpdadeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JIRAPortalCliente.getAttachmentsIssueResponse> JIRAPortalCliente.ServicoPortalClientePortType.getAttachmentsIssueAsync(JIRAPortalCliente.getAttachmentsIssueRequest request)
        {
            return base.Channel.getAttachmentsIssueAsync(request);
        }
        
        public System.Threading.Tasks.Task<JIRAPortalCliente.getAttachmentsIssueResponse> getAttachmentsIssueAsync(string issueKey)
        {
            JIRAPortalCliente.getAttachmentsIssueRequest inValue = new JIRAPortalCliente.getAttachmentsIssueRequest();
            inValue.issueKey = issueKey;
            return ((JIRAPortalCliente.ServicoPortalClientePortType)(this)).getAttachmentsIssueAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoPortalClienteHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServicoPortalClienteHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoPortalClienteHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://vm2k8jra4dev3:8080/ServicosJIRA/services/ServicoPortalCliente.ServicoPortal" +
                        "ClienteHttpSoap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServicoPortalClienteHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://vm2k8jra4dev3:8080/ServicosJIRA/services/ServicoPortalCliente.ServicoPortal" +
                        "ClienteHttpSoap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        internal Task CriaDadosAtendimentoAPPAsync(string plate, string driverCpf, object odometer, string empty1, object getDetailInformation, object p1, object supplierCnpj, object p2, object p3, string empty2, string empty3, string empty4, string empty5, string empty6)
        {
            throw new NotImplementedException();
        }

        public enum EndpointConfiguration
        {
            
            ServicoPortalClienteHttpSoap11Endpoint,
            
            ServicoPortalClienteHttpSoap12Endpoint,
        }
    }
}
